# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  Major: '1'
  Minor: '0'
  Patch: '0'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects:  'src/HttpHelpers/HttpHelpers.csproj'
    arguments: '--configuration $(buildConfiguration) --version-suffix "-$(Build.BuildId)"'
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects:  '**/*Tests.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: 'pack'
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'
    packagesToPack: 'src/HttpHelpers/HttpHelpers.csproj'
    buildProperties: 'VersionSuffix=-$(Build.BuildId)'
- task: DotNetCoreCLI@2
  displayName: NuGet Push
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '0519d52d-4ba9-4252-8042-1e0a4fd14def'